use std::collections::HashMap;

pub fn convert_key_name(db_key: &str) -> String {
    let key_map: HashMap<&str, &str> = [
        ("Escape", "Esc"),
        ("F1", "F1"),
        ("F2", "F2"),
        ("F3", "F3"),
        ("F4", "F4"),
        ("F5", "F5"),
        ("F6", "F6"),
        ("F7", "F7"),
        ("F8", "F8"),
        ("F9", "F9"),
        ("F10", "F10"),
        ("F11", "F11"),
        ("F12", "F12"),
        ("Delete", "Del"),
        ("Insert", "Ins"),
        ("BackQuote", "`"),
        ("Num1", "1"),
        ("Num2", "2"),
        ("Num3", "3"),
        ("Num4", "4"),
        ("Num5", "5"),
        ("Num6", "6"),
        ("Num7", "7"),
        ("Num8", "8"),
        ("Num9", "9"),
        ("Num0", "0"),
        ("Minus", "-"),
        ("Equal", "="),
        ("Backspace", "Bck"),
        ("PageUp", "PgUp"),
        ("Tab", "Tab"),
        ("KeyQ", "Q"),
        ("KeyW", "W"),
        ("KeyE", "E"),
        ("KeyR", "R"),
        ("KeyT", "T"),
        ("KeyY", "Y"),
        ("KeyU", "U"),
        ("KeyI", "I"),
        ("KeyO", "O"),
        ("KeyP", "P"),
        ("LeftBracket", "["),
        ("RightBracket", "]"),
        ("BackSlash", "\\"),
        ("PageDown", "PgDn"),
        ("CapsLock", "Caps"),
        ("KeyA", "A"),
        ("KeyS", "S"),
        ("KeyD", "D"),
        ("KeyF", "F"),
        ("KeyG", "G"),
        ("KeyH", "H"),
        ("KeyJ", "J"),
        ("KeyK", "K"),
        ("KeyL", "L"),
        ("SemiColon", ";"),
        ("Quote", "'"),
        ("Return", "Return"),
        ("Home", "Home"),
        ("ShiftLeft", "LShift"),
        ("KeyZ", "Z"),
        ("KeyX", "X"),
        ("KeyC", "C"),
        ("KeyV", "V"),
        ("KeyB", "B"),
        ("KeyN", "N"),
        ("KeyM", "M"),
        ("Comma", ","),
        ("Dot", "."),
        ("Slash", "/"),
        ("ShiftRight", "RShift"),
        ("ArrowUp", "↑"),
        ("End", "End"),
        ("ControlLeft", "LCtrl"),
        ("MetaLeft", "Win"),
        ("AltLeft", "LAlt"),
        ("Space", "Space"),
        ("RightAlt", "RAlt"),
        ("MetaRight", "Fn"),
        ("ControlRight", "RCtrl"),
        ("ArrowLeft", "←"),
        ("ArrowDown", "↓"),
        ("ArrownRight", "→"),
    ]
    .iter()
    .cloned()
    .collect();

    key_map
        .get(db_key)
        .map(|&s| s.to_string())
        .unwrap_or_else(|| db_key.to_string())
}
